### ISSUE TITLE
How to write and read binary

### ISSUE THREAD

**Issue by solsson** [Yolean/kafka-cache#14]
Having a `Buffer`, wanting a `Buffer`

**Comment by atamon** [comment]
Maybe we should take the time to write a [custom encoding](https://github.com/Level/encoding-down#custom-encodings) for encoding-down that addresses the use-case we had when we stumbled upon this: gzip.

**Comment by atamon** [comment]
We solved our initial need with gzipped buffers a while ago. Closing
